"""empty message

Revision ID: 96366df31788
Revises: ea9ce3ffc5a2
Create Date: 2023-07-09 10:26:42.405622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96366df31788'
down_revision = 'ea9ce3ffc5a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
